# Generated by Django 3.2.4 on 2021-06-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Category', models.CharField(default='', max_length=50)),
                ('Price', models.IntegerField(default=0)),
                ('Quantity', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('Image', models.ImageField(upload_to='SR_Catalogue/images')),
            ],
        ),
    ]
