# Generated by Django 3.2.4 on 2021-06-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SR_Catalogue', '0002_rename_remote_remotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotes',
            name='Category',
            field=models.CharField(default='Remote', max_length=50),
        ),
    ]
