# Generated by Django 3.2.4 on 2021-06-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SR_Catalogue', '0004_diwali_lights_dth_extension_ic_transistor_leads_led_miscellaneous_soundsystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundsystem',
            name='Category',
            field=models.CharField(default='Sound System', max_length=50),
        ),
    ]
