# Generated by Django 3.2.4 on 2021-06-17 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SR_Catalogue', '0005_alter_soundsystem_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SoundSystem',
            new_name='SoundSystems',
        ),
    ]
