# Generated by Django 3.2.4 on 2021-06-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SR_Catalogue', '0006_rename_soundsystem_soundsystems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diwali_Light',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Category', models.CharField(default='Diwali Lights', max_length=50)),
                ('Price', models.IntegerField(default=0)),
                ('Quantity', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('Image', models.ImageField(upload_to='SR_Catalogue/images')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Category', models.CharField(default='Leads', max_length=50)),
                ('Price', models.IntegerField(default=0)),
                ('Quantity', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('Image', models.ImageField(upload_to='SR_Catalogue/images')),
            ],
        ),
        migrations.RenameModel(
            old_name='Diwali_Lights',
            new_name='Remote',
        ),
        migrations.RenameModel(
            old_name='SoundSystems',
            new_name='SoundSystem',
        ),
        migrations.DeleteModel(
            name='Leads',
        ),
        migrations.DeleteModel(
            name='Remotes',
        ),
        migrations.AlterField(
            model_name='dth',
            name='Category',
            field=models.CharField(default='DTH', max_length=50),
        ),
        migrations.AlterField(
            model_name='extension',
            name='Category',
            field=models.CharField(default='Extension', max_length=50),
        ),
        migrations.AlterField(
            model_name='ic_transistor',
            name='Category',
            field=models.CharField(default='IC & Transistors', max_length=50),
        ),
        migrations.AlterField(
            model_name='led',
            name='Category',
            field=models.CharField(default='LED', max_length=50),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='Category',
            field=models.CharField(default='Miscellaneous', max_length=50),
        ),
    ]
