# Generated by Django 3.2.4 on 2021-06-17 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SR_Catalogue', '0008_display'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Display',
            new_name='Carousel',
        ),
    ]
