# Generated by Django 3.2.4 on 2021-06-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SR_Catalogue', '0009_rename_display_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Price', models.IntegerField(default=0)),
                ('Quantity', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('Image', models.ImageField(upload_to='SR_Catalogue/images')),
                ('Category', models.CharField(default='ABC', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Carousel',
        ),
        migrations.DeleteModel(
            name='Diwali_Light',
        ),
        migrations.DeleteModel(
            name='DTH',
        ),
        migrations.DeleteModel(
            name='Extension',
        ),
        migrations.DeleteModel(
            name='IC_Transistor',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
        migrations.DeleteModel(
            name='LED',
        ),
        migrations.DeleteModel(
            name='Miscellaneous',
        ),
        migrations.DeleteModel(
            name='Remote',
        ),
        migrations.DeleteModel(
            name='SoundSystem',
        ),
    ]
