# Generated by Django 3.2.4 on 2021-06-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SR_Catalogue', '0010_auto_20210618_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Image', models.ImageField(upload_to='SR_Catalogue/images')),
                ('Type_Of_Item', models.CharField(choices=[('Remote', '/remote'), ('IC Transistor', '/IC_Transistor'), ('Sound System', '/SoundSystem'), ('Extension', '/Extension'), ('Diwali Lights', '/DiwaliLights'), ('DTH', '/DTH'), ('Miscellaneous', '/Miscellaneous'), ('Leads', '/Leads'), ('LED', '/LED')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Diwali_Light',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Price', models.IntegerField(default=0)),
                ('Quantity', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('Image', models.ImageField(upload_to='SR_Catalogue/images')),
                ('Category', models.CharField(default='Diwali Lights', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DTH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Price', models.IntegerField(default=0)),
                ('Quantity', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('Image', models.ImageField(upload_to='SR_Catalogue/images')),
                ('Category', models.CharField(default='DTH', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Price', models.IntegerField(default=0)),
                ('Quantity', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('Image', models.ImageField(upload_to='SR_Catalogue/images')),
                ('Category', models.CharField(default='Extension', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IC_Transistor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Price', models.IntegerField(default=0)),
                ('Quantity', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('Image', models.ImageField(upload_to='SR_Catalogue/images')),
                ('Category', models.CharField(default='IC & Transistors', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Price', models.IntegerField(default=0)),
                ('Quantity', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('Image', models.ImageField(upload_to='SR_Catalogue/images')),
                ('Category', models.CharField(default='Leads', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Price', models.IntegerField(default=0)),
                ('Quantity', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('Image', models.ImageField(upload_to='SR_Catalogue/images')),
                ('Category', models.CharField(default='LED', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Miscellaneous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Price', models.IntegerField(default=0)),
                ('Quantity', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('Image', models.ImageField(upload_to='SR_Catalogue/images')),
                ('Category', models.CharField(default='Miscellaneous', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Remote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Price', models.IntegerField(default=0)),
                ('Quantity', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('Image', models.ImageField(upload_to='SR_Catalogue/images')),
                ('Category', models.CharField(default='Remote', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoundSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Price', models.IntegerField(default=0)),
                ('Quantity', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('Image', models.ImageField(upload_to='SR_Catalogue/images')),
                ('Category', models.CharField(default='Sound System', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Abc',
        ),
    ]
