# Generated by Django 3.2.4 on 2021-06-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SR_Catalogue', '0011_auto_20210618_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='Type_Of_Item',
            field=models.CharField(choices=[('/remote', 'Remote'), ('/IC_Transistor', 'IC Transistor'), ('/SoundSystem', 'Sound System'), ('/Extension', 'Extension'), ('/DiwaliLights', 'Diwali Lights'), ('/DTH', 'DTH'), ('/Miscellaneous', 'Miscellaneous'), ('/Leads', 'Leads'), ('/LED', 'LED')], max_length=30),
        ),
    ]
