# Generated by Django 3.2.4 on 2021-06-18 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SR_Catalogue', '0013_carousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diwali_light',
            name='date',
        ),
        migrations.RemoveField(
            model_name='dth',
            name='date',
        ),
        migrations.RemoveField(
            model_name='extension',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ic_transistor',
            name='date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='date',
        ),
        migrations.RemoveField(
            model_name='led',
            name='date',
        ),
        migrations.RemoveField(
            model_name='miscellaneous',
            name='date',
        ),
        migrations.RemoveField(
            model_name='remote',
            name='date',
        ),
        migrations.RemoveField(
            model_name='soundsystem',
            name='date',
        ),
    ]
