# Generated by Django 3.2.4 on 2021-07-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SR_Catalogue', '0016_alter_display_type_of_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diwali_light',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to='SR_Catalogue/images'),
        ),
        migrations.AlterField(
            model_name='diwali_light',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to='SR_Catalogue/images'),
        ),
        migrations.AlterField(
            model_name='dth',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to='SR_Catalogue/images'),
        ),
        migrations.AlterField(
            model_name='dth',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to='SR_Catalogue/images'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to='SR_Catalogue/images'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to='SR_Catalogue/images'),
        ),
        migrations.AlterField(
            model_name='ic_transistor',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to='SR_Catalogue/images'),
        ),
        migrations.AlterField(
            model_name='ic_transistor',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to='SR_Catalogue/images'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to='SR_Catalogue/images'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to='SR_Catalogue/images'),
        ),
        migrations.AlterField(
            model_name='led',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to='SR_Catalogue/images'),
        ),
        migrations.AlterField(
            model_name='led',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to='SR_Catalogue/images'),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to='SR_Catalogue/images'),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to='SR_Catalogue/images'),
        ),
        migrations.AlterField(
            model_name='remote',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to='SR_Catalogue/images'),
        ),
        migrations.AlterField(
            model_name='remote',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to='SR_Catalogue/images'),
        ),
        migrations.AlterField(
            model_name='soundsystem',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to='SR_Catalogue/images'),
        ),
        migrations.AlterField(
            model_name='soundsystem',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to='SR_Catalogue/images'),
        ),
    ]
